`Consider the below code to answer further questions:`


In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

`Question 1`. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

`Answer` :Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list while array_list is a NumPy array.

In [6]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


`Question 2`. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [13]:
variables_list_type = []
arra_list_type = []
for element in list_:
    variables_list_type.append(type(element))
    
for element in array_list:
    arra_list_type.append(type(element))
    
print(variables_list_type)
print('______________________________________________________________________________________________________________')
print(arra_list_type)

[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
______________________________________________________________________________________________________________
[<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>]


Q3. Considering the following changes in the variable, array_list:

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [14]:
array_list = np.array(object = list_, dtype = int)

In [16]:
print(type(array_list))
for element in array_list:
    print(type(element))

<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


`Answer`

Yes, there will be a difference in the data type of the elements present in `list_` and `array_list` if you change the data type of the array using the dtype parameter.

By setting dtype to `int`, the elements in `array_list` will be cast to `integer type`.

`Consider the below code to answer further questions:`

In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [18]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

`Question 4`. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size


In [25]:
print(num_array.shape)
print("________")
print(num_array.size)

(2, 3)
________
6


`Question 5`. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [32]:
arr1 = np.zeros((3,3))
print(arr1)

print("____________")

print(arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
____________
(3, 3)


`Question 6`. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [33]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


`Completed`