# <div style="padding: 10px; background-color: #64CCC5; margin: 10px; color: #000000; font-family: 'New Times Roman', serif; font-size: 60%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> Question 1: Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.</div>

In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

import warnings
warnings.filterwarnings('ignore')

In [57]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

In [58]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [59]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [60]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


1.0

# <div style="padding: 10px; background-color: #64CCC5; margin: 10px; color: #000000; font-family: 'New Times Roman', serif; font-size: 60%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> Question 2: Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.</div>

In [61]:
#`load_boston` has been removed from scikit-learn since version 1.2.
from sklearn.datasets import fetch_california_housing
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Load the California housing dataset
california_housing = fetch_california_housing()

# Separate the feature matrix (X) and the target variable (y)
X = pd.DataFrame(california_housing.data, columns=california_housing.feature_names)
y = pd.Series(california_housing.target, name='TARGET')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [62]:
# Create and train the KNN regressor
knn_regressor = KNeighborsRegressor(n_neighbors=5)
knn_regressor.fit(X_train, y_train)

KNeighborsRegressor()

In [63]:
# Make predictions on the test set
y_pred = knn_regressor.predict(X_test)

# Evaluate the model's performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse:.4f}')
print(f'R-squared: {r2:.4f}')

Mean Squared Error: 1.1187
R-squared: 0.1463


# <div style="padding: 10px; background-color: #64CCC5; margin: 10px; color: #000000; font-family: 'New Times Roman', serif; font-size: 60%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> Question 3: Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.</div>

In [64]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score, KFold

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Define a range of K values to try
k_values = np.arange(1, 21)

# Perform cross-validation for each K value
cv_scores = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    # Use 5-fold cross-validation
    scores = cross_val_score(knn, X, y, cv=KFold(n_splits=5, shuffle=True, random_state=42))
    cv_scores.append(np.mean(scores))

# Find the optimal K value
optimal_k = k_values[np.argmax(cv_scores)]

# Print the results
print(f'Optimal K value: {optimal_k}')


Optimal K value: 13


# <div style="padding: 10px; background-color: #64CCC5; margin: 10px; color: #000000; font-family: 'New Times Roman', serif; font-size: 60%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> Question4:Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.</div>

In [65]:
#`load_boston` has been removed from scikit-learn since version 1.2.
from sklearn.datasets import fetch_california_housing
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Load the California housing dataset
california_housing = fetch_california_housing()

# Separate the feature matrix (X) and the target variable (y)
X = pd.DataFrame(california_housing.data, columns=california_housing.feature_names)
y = pd.Series(california_housing.target, name='TARGET')

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [66]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [67]:
# Create and train the KNN regressor
knn_regressor = KNeighborsRegressor(n_neighbors=5)
knn_regressor.fit(X_train, y_train)

KNeighborsRegressor()

In [68]:
# Make predictions on the test set
y_pred = knn_regressor.predict(X_test)

# Evaluate the model's performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse:.4f}')
print(f'R-squared: {r2:.4f}')

Mean Squared Error: 0.4324
R-squared: 0.6700


# <div style="padding: 10px; background-color: #64CCC5; margin: 10px; color: #000000; font-family: 'New Times Roman', serif; font-size: 60%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> Question 5: Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.</div>

In [69]:
#`load_boston` has been removed from scikit-learn since version 1.2.

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the KNN classifier with weighted voting
knn_classifier = KNeighborsClassifier(n_neighbors=5, weights='distance')
knn_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = knn_classifier.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.4f}')


Accuracy: 1.0000


# <div style="padding: 10px; background-color: #64CCC5; margin: 10px; color: #000000; font-family: 'New Times Roman', serif; font-size: 60%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> Question 6: Implement a function to standardise the features before applying KNN classifier.</div>

In [70]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def knn_classifier_with_standardization(X_train, X_test, y_train, y_test, n_neighbors=5):
    # Standardize the features
    scaler = StandardScaler()
    X_train_std = scaler.fit_transform(X_train)
    X_test_std = scaler.transform(X_test)

    # Create and train the KNN classifier
    knn_classifier = KNeighborsClassifier(n_neighbors=n_neighbors)
    knn_classifier.fit(X_train_std, y_train)

    # Make predictions on the standardized test set
    y_pred = knn_classifier.predict(X_test_std)

    # Evaluate the model's performance
    accuracy = accuracy_score(y_test, y_pred)
    print(f'Accuracy: {accuracy:.4f}')

# Example usage with the load_iris dataset
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply the KNN classifier with standardization
knn_classifier_with_standardization(X_train, X_test, y_train, y_test, n_neighbors=5)


Accuracy: 1.0000


# <div style="padding: 10px; background-color: #64CCC5; margin: 10px; color: #000000; font-family: 'New Times Roman', serif; font-size: 60%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> Question 7: Write a Python function to calculate the euclidean distance between two points.</div>

In [71]:
import numpy as np

def euclidean_distance(point1, point2):
    """
    Calculate the Euclidean distance between two points.

    Parameters:
    - point1: Tuple or array-like, representing the coordinates of the first point.
    - point2: Tuple or array-like, representing the coordinates of the second point.

    Returns:
    - distance: Euclidean distance between the two points.
    """
    point1 = np.array(point1)
    point2 = np.array(point2)

    distance = np.sqrt(np.sum((point2 - point1)**2))
    return distance

# Example usage:
point1 = (1, 2)
point2 = (4, 6)

distance = euclidean_distance(point1, point2)
print(f'Euclidean Distance between {point1} and {point2}: {distance:.4f}')


Euclidean Distance between (1, 2) and (4, 6): 5.0000


# <div style="padding: 10px; background-color: #64CCC5; margin: 10px; color: #000000; font-family: 'New Times Roman', serif; font-size: 60%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> Question 8: Write a Python function to calculate the manhattan distance between two points.</div>

In [72]:
import numpy as np

def manhattan_distance(point1, point2):
    """
    Calculate the Manhattan distance between two points.

    Parameters:
    - point1: Tuple or array-like, representing the coordinates of the first point.
    - point2: Tuple or array-like, representing the coordinates of the second point.

    Returns:
    - distance: Manhattan distance between the two points.
    """
    point1 = np.array(point1)
    point2 = np.array(point2)

    distance = np.sum(np.abs(point2 - point1))
    return distance

# Example usage:
point1 = (1, 2)
point2 = (4, 6)

distance = manhattan_distance(point1, point2)
print(f'Manhattan Distance between {point1} and {point2}: {distance}')


Manhattan Distance between (1, 2) and (4, 6): 7


# <div style="padding: 15px; background-color: #D2E0FB; margin: 15px; color: #000000; font-family: 'New Times Roman', serif; font-size: 110%; text-align: center; border-radius: 10px; overflow: hidden; font-weight: bold;"> ***...Complete...***</div>